#main.yml: aws ec2 inventory.
- name: EC2 inventario
  plugin: aws_ec2
  regions:
    - "{{ lookup('env','TF_VAR_aws_region') }}"
  keyed_groups:
    - key: tags.Name
      prefix: ec2_name_
  aws_access_key: "{{ lookup('env','TF_VAR_aws_ak') }}"
  aws_secret_key: "{{ lookup('env','TF_VAR_aws_sk') }}"