---
#main.yml: kong-ce tasks.
  - name: Instalar Pip
    become: yes
    apt:
      name: ['python-pip']
      state: present
  - name: Docker python module
    become: yes
    pip:
      name: docker
  - name: Create a network for kong
    become: yes
    docker_network:
      name: kong-net
  - name: Pull kong-ce image
    become: yes
    docker_image:
      name: "kong:alpine"
      source: pull
  - name: Pull postgress 9.6 image
    become: yes
    docker_image:
      name: "postgres:9.6"
      source: pull
  - name: Create database container
    become: yes
    docker_container:
      name: kongdb
      image: "postgres:9.6"
      state: started
      networks:
        - name: "kong-net"
      ports:
       - "5555:5432"
      env:
         POSTGRES_USER: "kong"
         POSTGRES_DB: "kong"
  - name: Database migrations
    become: yes
    docker_container:
      name: kong
      image: "kong:latest"
      networks:
        - name: "kong-net"
      env:
         KONG_DATABASE: "postgres"
         KONG_PG_HOST: "kongdb"
      command: kong migrations bootstrap
  - name: Create kong container
    become: yes
    docker_container:
      name: kong
      image: "kong:latest"
      state: started
      networks:
        - name: "kong-net"
      ports:
       - "9000:8000"
       - "9443:8443"
       - "9001:8001"
       - "9444:8444"
      env:
         KONG_LOG_LEVEL: "debug"
         KONG_DATABASE: "postgres"
         KONG_PG_HOST: "kongdb"
         KONG_PROXY_ACCESS_LOG: "/dev/stdout"
         KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
         KONG_PROXY_ERROR_LOG: "/dev/stderr"
         KONG_ADMIN_ERROR_LOG: "/dev/stderr"
         KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"

