name: CI Demo Bennu

on:
  push:
    branches: 
      - task-ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update local env
      run: sudo apt-get update
    - name: Install dependencies
      run: |
        sudo apt-get install -y wget
        sudo apt-get install -y unzip
        sudo apt-get install -y python3
        sudo apt-get install -y python3-pip
        sudo apt-get install -y python
        sudo apt-get install -y python-pip
        sudo apt-get install -y ansible
        sudo apt-get install -y awscli
        sudo apt-get install python3-setuptools
        sudo apt-get install python-setuptools
    - name: Pip dependencies
      run: |
        pip3 install awscli
        pip3 install ansible
    - name: Install Terraform
      run: |
        cd /opt/
        sudo wget https://releases.hashicorp.com/terraform/0.12.17/terraform_0.12.17_linux_amd64.zip
        sudo unzip terraform_0.12.17_linux_amd64.zip
        sudo cp -f ./terraform /usr/local/bin
        sudo cp -f ./terraform /bin
      env:
        TF_VAR_ec2_key_priv: ${{ secrets.var_ec2_key_priv }}
    - name: Create key
      run: |
        echo $TF_VAR_ec2_key_priv > ./terraform/tempkey
        chmod 600 ./terraform/tempkey
        ls -l ./terraform/
      env:
        TF_VAR_ec2_key_priv: ${{ secrets.var_ec2_key_priv }}
    - name: Terraform Task init
      run: |
        cd terraform && terraform init
    - name: Terraform Task validate
      run: |
        cd terraform && terraform validate
      env:
        TF_VAR_aws_ak: ${{ secrets.var_aws_ak }}
        TF_VAR_aws_sk: ${{ secrets.var_aws_sk }}
        TF_VAR_aws_region: ${{ secrets.var_aws_region }}
        TF_VAR_ec2_name: ${{ secrets.var_ec2_name }}
        TF_VAR_ec2_ami_id: ${{ secrets.var_ec2_ami_id }}
        TF_VAR_ec2_sg_name: ${{ secrets.var_ec2_sg_name }}
        TF_VAR_ec2_key_pub: ${{ secrets.var_ec2_key_pub }}
        TF_VAR_ec2_key_priv: ${{ secrets.var_ec2_key_priv }}
    - name: Terraform Task plan
      run: |
        cd terraform && terraform plan
      env:
        TF_VAR_aws_ak: ${{ secrets.var_aws_ak }}
        TF_VAR_aws_sk: ${{ secrets.var_aws_sk }}
        TF_VAR_aws_region: ${{ secrets.var_aws_region }}
        TF_VAR_ec2_name: ${{ secrets.var_ec2_name }}
        TF_VAR_ec2_ami_id: ${{ secrets.var_ec2_ami_id }}
        TF_VAR_ec2_sg_name: ${{ secrets.var_ec2_sg_name }}
        TF_VAR_ec2_key_pub: ${{ secrets.var_ec2_key_pub }}
        TF_VAR_ec2_key_priv: ${{ secrets.var_ec2_key_priv }}
    - name: Terraform Task apply
      run: |
        cd terraform &&terraform apply -auto-approve
      env:
        TF_VAR_aws_ak: ${{ secrets.var_aws_ak }}
        TF_VAR_aws_sk: ${{ secrets.var_aws_sk }}
        TF_VAR_aws_region: ${{ secrets.var_aws_region }}
        TF_VAR_ec2_name: ${{ secrets.var_ec2_name }}
        TF_VAR_ec2_ami_id: ${{ secrets.var_ec2_ami_id }}
        TF_VAR_ec2_sg_name: ${{ secrets.var_ec2_sg_name }}
        TF_VAR_ec2_key_pub: ${{ secrets.var_ec2_key_pub }}
        TF_VAR_ec2_key_priv: ${{ secrets.var_ec2_key_priv }}
