name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update local env
      run: apt-get update
    - name: Install dependencies
      run: |
        apt-get install -y python3
        apt-get install -y python3-pip
        apt-get install -y python
        apt-get install -y python-pip
        apt-get install -y ansible
