name: CI Demo Bennu

on:
  push:
    branches: 
      - task-ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update local env
      run: sudo apt-get update
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3
        sudo apt-get install -y python3-pip
        sudo apt-get install -y python
        sudo apt-get install -y python-pip
        sudo apt-get install -y ansible
        sudo apt-get install -y awscli
        sudo apt-get install python3-setuptools
        sudo apt-get install python-setuptools
    - name: Pip dependencies
      run: |
        pip3 install awscli
        pip3 install ansible
    - name: Create key
      run: |
        echo ${{ secrets.var_ec2_key_priv }} > /tmp/tempkey
        chmod 600 /tmp/tempkey
    - name: Terraform Task init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: './terraform'
    - name: Terraform Task validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: './terraform'
      env:
        TF_VAR_aws_ak: ${{ secrets.var_aws_ak }}
        TF_VAR_aws_sk: ${{ secrets.var_aws_sk }}
        TF_VAR_aws_region: ${{ secrets.var_aws_region }}
        TF_VAR_ec2_name: ${{ secrets.var_ec2_name }}
        TF_VAR_ec2_ami_id: ${{ secrets.var_ec2_ami_id }}
        TF_VAR_ec2_sg_name: ${{ secrets.var_ec2_sg_name }}
        TF_VAR_ec2_key_pub: ${{ secrets.var_ec2_key_pub }}
        TF_VAR_ec2_key_priv: ${{ secrets.var_ec2_key_priv }}
    - name: Terraform Task plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: './terraform'
      env:
        TF_VAR_aws_ak: ${{ secrets.var_aws_ak }}
        TF_VAR_aws_sk: ${{ secrets.var_aws_sk }}
        TF_VAR_aws_region: ${{ secrets.var_aws_region }}
        TF_VAR_ec2_name: ${{ secrets.var_ec2_name }}
        TF_VAR_ec2_ami_id: ${{ secrets.var_ec2_ami_id }}
        TF_VAR_ec2_sg_name: ${{ secrets.var_ec2_sg_name }}
        TF_VAR_ec2_key_pub: ${{ secrets.var_ec2_key_pub }}
        TF_VAR_ec2_key_priv: ${{ secrets.var_ec2_key_priv }}
    - name: Terraform Task apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: './terraform'
      env:
        TF_VAR_aws_ak: ${{ secrets.var_aws_ak }}
        TF_VAR_aws_sk: ${{ secrets.var_aws_sk }}
        TF_VAR_aws_region: ${{ secrets.var_aws_region }}
        TF_VAR_ec2_name: ${{ secrets.var_ec2_name }}
        TF_VAR_ec2_ami_id: ${{ secrets.var_ec2_ami_id }}
        TF_VAR_ec2_sg_name: ${{ secrets.var_ec2_sg_name }}
        TF_VAR_ec2_key_pub: ${{ secrets.var_ec2_key_pub }}
        TF_VAR_ec2_key_priv: ${{ secrets.var_ec2_key_priv }}
